(defpackage #:cl-llama-cpp/generate
  (:use #:cl)
  (:export #:generate))

(in-package #:cl-llama-cpp/generate)

(defun project-path (relative)
  (namestring (merge-pathnames relative
                               (asdf:system-source-directory "cl-llama-cpp"))))

(defun build-wrapper-form ()
  `(claw:defwrapper (:cl-llama-cpp
                     (:headers "llama.h")
                     (:includes ,(project-path "llama.cpp/include/")
                                ,(project-path "llama.cpp/ggml/include/"))
                     (:spec-path ,(project-path "spec/"))
                     (:include-definitions "^(llama|LLAMA)_\\w+")
                     (:language :c))
     :in-package :%llama
     :trim-enum-prefix t
     :recognize-bitfields t
     :recognize-strings t
     :recognize-arrays t
     :symbolicate-names (:in-pipeline
                         (:by-removing-prefixes "llama_" "LLAMA_"))))

(defun write-bindings (expansion output)
  (with-open-file (out output :direction :output
                              :if-exists :supersede
                              :external-format :utf-8)
    (let ((*package* (find-package :%llama))
          (*print-case* :downcase)
          (*print-pretty* t)
          (*print-right-margin* 100))
      (format out ";;;; Auto-generated CFFI bindings for llama.cpp~%")
      (format out ";;;; Generated by cl-llama-cpp/generate -- DO NOT EDIT~%~%")
      (format out "(in-package #:%llama)~%~%")
      (labels ((emit (form)
                 (cond
                   ((and (listp form) (eq (car form) 'progn))
                    (dolist (f (cdr form)) (emit f)))
                   ((and (listp form) (member (car form)
                                              '(cffi:defcfun cffi:defcstruct cffi:defcenum
                                                cffi:defctype defparameter declaim export)))
                    (pprint form out)
                    (terpri out)
                    (terpri out))
                   (t
                    (pprint form out)
                    (terpri out)
                    (terpri out)))))
        (emit expansion)))))

(defun generate (&key (output (project-path "src/bindings.lisp"))
                      rebuild-spec)
  "Generate CFFI bindings from llama.h via CLAW.
When REBUILD-SPEC is true, force c2ffi to re-parse headers even if
spec files exist (use after bumping the llama.cpp submodule)."
  (when rebuild-spec
    (pushnew :claw-rebuild-spec *features*))
  (pushnew :claw-local-only *features*)
  (let* ((form (build-wrapper-form))
         (expansion (macroexpand-1 form)))
    (write-bindings expansion output)
    (format t "~&Bindings written to ~a~%" output)
    output))
