;;;; Auto-generated CFFI bindings for llama.cpp
;;;; Generated by cl-llama-cpp/generate -- DO NOT EDIT

(in-package #:%llama)


(common-lisp:defparameter +default-seed+ 4294967295)


(common-lisp:defparameter +file-magic-ggla+ 1734831201)


(common-lisp:defparameter +file-magic-ggsn+ 1734833006)


(common-lisp:defparameter +file-magic-ggsq+ 1734833009)


(common-lisp:defparameter +session-magic+ 1734833006)


(common-lisp:defparameter +session-version+ 9)


(common-lisp:defparameter +state-seq-flags-none+ 0)


(common-lisp:defparameter +state-seq-flags-on-device+ 2)


(common-lisp:defparameter +state-seq-flags-partial-only+ 1)


(common-lisp:defparameter +state-seq-flags-swa-only+ 1)


(common-lisp:defparameter +state-seq-magic+ 1734833009)


(common-lisp:defparameter +state-seq-version+ 2)


(common-lisp:defparameter +token-null+ -1)


(cffi:defctype size-t :unsigned-long)


(cffi:defctype %%int8-t :char)


(cffi:defctype %%uint8-t :unsigned-char)


(cffi:defctype %%int32-t :int)


(cffi:defctype %%uint32-t :unsigned-int)


(cffi:defctype %%int64-t :long)


(cffi:defctype %%uint64-t :unsigned-long)


(cffi:defctype int8-t :char)


(cffi:defctype int32-t :int)


(cffi:defctype int64-t :long)


(cffi:defctype uint8-t :unsigned-char)


(cffi:defctype uint32-t :unsigned-int)


(cffi:defctype uint64-t :unsigned-long)


(cffi:defcstruct (%io-file :size 216))


(cffi:defctype file (:struct %io-file))


(cffi:defcenum ggml-type
  (:f32 0)
  (:f16 1)
  (:q4-0 2)
  (:q4-1 3)
  (:q5-0 6)
  (:q5-1 7)
  (:q8-0 8)
  (:q8-1 9)
  (:q2-k 10)
  (:q3-k 11)
  (:q4-k 12)
  (:q5-k 13)
  (:q6-k 14)
  (:q8-k 15)
  (:iq2-xxs 16)
  (:iq2-xs 17)
  (:iq3-xxs 18)
  (:iq1-s 19)
  (:iq4-nl 20)
  (:iq3-s 21)
  (:iq2-s 22)
  (:iq4-xs 23)
  (:i8 24)
  (:i16 25)
  (:i32 26)
  (:i64 27)
  (:f64 28)
  (:iq1-m 29)
  (:bf16 30)
  (:tq1-0 34)
  (:tq2-0 35)
  (:mxfp4 39)
  (:nvfp4 40)
  (:q1-0 41)
  (:count 42))


(cffi:defcstruct (ggml-tensor :size 336))


(cffi:defctype ggml-abort-callback (:pointer :void))


(cffi:defctype ggml-log-callback (:pointer :void))


(cffi:defcstruct ggml-threadpool)


(cffi:defctype ggml-threadpool-t (:pointer (:struct ggml-threadpool)))


(cffi:defcstruct ggml-backend-buffer-type)


(cffi:defctype ggml-backend-buffer-type-t (:pointer (:struct ggml-backend-buffer-type)))


(cffi:defcstruct ggml-backend-device)


(cffi:defctype ggml-backend-dev-t (:pointer (:struct ggml-backend-device)))


(cffi:defctype ggml-backend-sched-eval-callback (:pointer :void))


(cffi:defcenum ggml-numa-strategy
  (:disabled 0)
  (:distribute 1)
  (:isolate 2)
  (:numactl 3)
  (:mirror 4)
  (:count 5))


(cffi:defcstruct ggml-opt-dataset)


(cffi:defctype ggml-opt-dataset-t (:pointer (:struct ggml-opt-dataset)))


(cffi:defcstruct ggml-opt-result)


(cffi:defctype ggml-opt-result-t (:pointer (:struct ggml-opt-result)))


(cffi:defcenum ggml-opt-optimizer-type
  (:adamw 0)
  (:sgd 1)
  (:count 2))


(cffi:defctype ggml-opt-get-optimizer-params (:pointer :void))


(cffi:defctype ggml-opt-epoch-callback (:pointer :void))


(cffi:defcstruct memory-i)


(cffi:defctype memory-t (:pointer (:struct memory-i)))


(cffi:defctype pos :int)


(cffi:defctype token :int)


(cffi:defctype seq-id :int)


(cffi:defcenum vocab-type
  (:none 0)
  (:spm 1)
  (:bpe 2)
  (:wpm 3)
  (:ugm 4)
  (:rwkv 5)
  (:plamo2 6))


(cffi:defcenum rope-type
  (:none 4294967295)
  (:norm 0)
  (:neox 2)
  (:mrope 8)
  (:imrope 40)
  (:vision 24))


(cffi:defcenum token-type
  (:undefined 0)
  (:normal 1)
  (:unknown 2)
  (:control 3)
  (:user-defined 4)
  (:unused 5)
  (:byte 6))


(cffi:defcenum token-attr
  (:undefined 0)
  (:unknown 1)
  (:unused 2)
  (:normal 4)
  (:control 8)
  (:user-defined 16)
  (:byte 32)
  (:normalized 64)
  (:lstrip 128)
  (:rstrip 256)
  (:single-word 512))


(cffi:defcenum ftype
  (:all-f32 0)
  (:mostly-f16 1)
  (:mostly-q4-0 2)
  (:mostly-q4-1 3)
  (:mostly-q8-0 7)
  (:mostly-q5-0 8)
  (:mostly-q5-1 9)
  (:mostly-q2-k 10)
  (:mostly-q3-k-s 11)
  (:mostly-q3-k-m 12)
  (:mostly-q3-k-l 13)
  (:mostly-q4-k-s 14)
  (:mostly-q4-k-m 15)
  (:mostly-q5-k-s 16)
  (:mostly-q5-k-m 17)
  (:mostly-q6-k 18)
  (:mostly-iq2-xxs 19)
  (:mostly-iq2-xs 20)
  (:mostly-q2-k-s 21)
  (:mostly-iq3-xs 22)
  (:mostly-iq3-xxs 23)
  (:mostly-iq1-s 24)
  (:mostly-iq4-nl 25)
  (:mostly-iq3-s 26)
  (:mostly-iq3-m 27)
  (:mostly-iq2-s 28)
  (:mostly-iq2-m 29)
  (:mostly-iq4-xs 30)
  (:mostly-iq1-m 31)
  (:mostly-bf16 32)
  (:mostly-tq1-0 36)
  (:mostly-tq2-0 37)
  (:mostly-mxfp4-moe 38)
  (:mostly-nvfp4 39)
  (:mostly-q1-0 40)
  (:guessed 1024))


(cffi:defcenum rope-scaling-type
  (:unspecified 4294967295)
  (:none 0)
  (:linear 1)
  (:yarn 2)
  (:longrope 3)
  (:max-value 3))


(cffi:defcenum pooling-type
  (:unspecified 4294967295)
  (:none 0)
  (:mean 1)
  (:cls 2)
  (:last 3)
  (:rank 4))


(cffi:defcenum attention-type
  (:unspecified 4294967295)
  (:causal 0)
  (:non-causal 1))


(cffi:defcenum flash-attn-type
  (:auto 4294967295)
  (:disabled 0)
  (:enabled 1))


(cffi:defcfun ("llama_flash_attn_type_name" flash-attn-type-name)
    :string
  "char* llama_flash_attn_type_name(enum llama_flash_attn_type flash_attn_type);"
  (flash-attn-type flash-attn-type))


(cffi:defcenum split-mode
  (:none 0)
  (:layer 1)
  (:row 2)
  (:tensor 3))


(cffi:defcenum context-type
  (:default 0)
  (:mtp 1))


(cffi:defcstruct (token-data :size 12)
  (id token :offset 0)
  (logit :float :offset 4)
  (p :float :offset 8))


(cffi:defctype token-data (:struct token-data))


(cffi:defcstruct (token-data-array :size 32)
  (data (:pointer token-data) :offset 0)
  (size size-t :offset 8)
  (selected int64-t :offset 16)
  (sorted :char :offset 24))


(cffi:defctype token-data-array (:struct token-data-array))


(cffi:defctype progress-callback (:pointer :void))


(cffi:defcstruct (batch :size 56)
  (n-tokens int32-t :offset 0)
  (token (:pointer token) :offset 8)
  (embd (:pointer :float) :offset 16)
  (pos (:pointer pos) :offset 24)
  (n-seq-id (:pointer int32-t) :offset 32)
  (seq-id (:pointer (:pointer seq-id)) :offset 40)
  (logits (:pointer int8-t) :offset 48))


(cffi:defctype batch (:struct batch))


(cffi:defcenum model-kv-override-type
  (:int 0)
  (:float 1)
  (:bool 2)
  (:str 3))


(cffi:defcenum model-meta-key
  (:sequence 0)
  (:top-k 1)
  (:top-p 2)
  (:min-p 3)
  (:xtc-probability 4)
  (:xtc-threshold 5)
  (:temp 6)
  (:penalty-last-n 7)
  (:penalty-repeat 8)
  (:mirostat 9)
  (:mirostat-tau 10)
  (:mirostat-eta 11))


(cffi:defcunion (model-kv-override-value :size 128)
  (val-i64 int64-t)
  (val-f64 :double)
  (val-bool :char)
  (val-str :char :count 128))


(cffi:defcstruct (model-kv-override :size 264)
  (tag model-kv-override-type :offset 0)
  (key :char :count 128 :offset 4)
  (value (:union model-kv-override-value) :offset 136))


(cffi:defcstruct (model-tensor-buft-override :size 16)
  (pattern :string :offset 0)
  (buft ggml-backend-buffer-type-t :offset 8))


(cffi:defcstruct (model-params :size 72)
  (devices (:pointer ggml-backend-dev-t) :offset 0)
  (tensor-buft-overrides (:pointer (:struct model-tensor-buft-override)) :offset 8)
  (n-gpu-layers int32-t :offset 16)
  (split-mode split-mode :offset 20)
  (main-gpu int32-t :offset 24)
  (tensor-split (:pointer :float) :offset 32)
  (progress-callback progress-callback :offset 40)
  (progress-callback-user-data (:pointer :void) :offset 48)
  (kv-overrides (:pointer (:struct model-kv-override)) :offset 56)
  (vocab-only :char :offset 64)
  (use-mmap :char :offset 65)
  (use-direct-io :char :offset 66)
  (use-mlock :char :offset 67)
  (check-tensors :char :offset 68)
  (use-extra-bufts :char :offset 69)
  (no-host :char :offset 70)
  (no-alloc :char :offset 71))


(cffi:defcstruct (sampler-i :size 80)
  (name (:pointer :void) :offset 0)
  (accept (:pointer :void) :offset 8)
  (apply (:pointer :void) :offset 16)
  (reset (:pointer :void) :offset 24)
  (clone (:pointer :void) :offset 32)
  (free (:pointer :void) :offset 40)
  (backend-init (:pointer :void) :offset 48)
  (backend-accept (:pointer :void) :offset 56)
  (backend-apply (:pointer :void) :offset 64)
  (backend-set-input (:pointer :void) :offset 72))


(cffi:defctype sampler-context-t (:pointer :void))


(cffi:defcstruct (sampler :size 16)
  (iface (:pointer (:struct sampler-i)) :offset 0)
  (ctx sampler-context-t :offset 8))


(cffi:defcstruct (sampler-seq-config :size 16)
  (seq-id seq-id :offset 0)
  (sampler (:pointer (:struct sampler)) :offset 8))


(cffi:defcstruct context)


(cffi:defcstruct (context-params :size 160)
  (n-ctx uint32-t :offset 0)
  (n-batch uint32-t :offset 4)
  (n-ubatch uint32-t :offset 8)
  (n-seq-max uint32-t :offset 12)
  (n-rs-seq uint32-t :offset 16)
  (n-outputs-max uint32-t :offset 20)
  (n-threads int32-t :offset 24)
  (n-threads-batch int32-t :offset 28)
  (ctx-type context-type :offset 32)
  (rope-scaling-type rope-scaling-type :offset 36)
  (pooling-type pooling-type :offset 40)
  (attention-type attention-type :offset 44)
  (flash-attn-type flash-attn-type :offset 48)
  (rope-freq-base :float :offset 52)
  (rope-freq-scale :float :offset 56)
  (yarn-ext-factor :float :offset 60)
  (yarn-attn-factor :float :offset 64)
  (yarn-beta-fast :float :offset 68)
  (yarn-beta-slow :float :offset 72)
  (yarn-orig-ctx uint32-t :offset 76)
  (defrag-thold :float :offset 80)
  (cb-eval ggml-backend-sched-eval-callback :offset 88)
  (cb-eval-user-data (:pointer :void) :offset 96)
  (type-k ggml-type :offset 104)
  (type-v ggml-type :offset 108)
  (abort-callback ggml-abort-callback :offset 112)
  (abort-callback-data (:pointer :void) :offset 120)
  (embeddings :char :offset 128)
  (offload-kqv :char :offset 129)
  (no-perf :char :offset 130)
  (op-offload :char :offset 131)
  (swa-full :char :offset 132)
  (kv-unified :char :offset 133)
  (samplers (:pointer (:struct sampler-seq-config)) :offset 136)
  (n-samplers size-t :offset 144)
  (ctx-other (:pointer (:struct context)) :offset 152))


(cffi:defcstruct (model-tensor-override :size 16)
  (pattern :string :offset 0)
  (type ggml-type :offset 8))


(cffi:defcstruct (model-imatrix-data :size 24)
  (name :string :offset 0)
  (data (:pointer :float) :offset 8)
  (size size-t :offset 16))


(cffi:defcstruct (model-quantize-params :size 56)
  (nthread int32-t :offset 0)
  (ftype ftype :offset 4)
  (output-tensor-type ggml-type :offset 8)
  (token-embedding-type ggml-type :offset 12)
  (allow-requantize :char :offset 16)
  (quantize-output-tensor :char :offset 17)
  (only-copy :char :offset 18)
  (pure :char :offset 19)
  (keep-split :char :offset 20)
  (dry-run :char :offset 21)
  (imatrix (:pointer (:struct model-imatrix-data)) :offset 24)
  (kv-overrides (:pointer (:struct model-kv-override)) :offset 32)
  (tt-overrides (:pointer (:struct model-tensor-override)) :offset 40)
  (prune-layers (:pointer int32-t) :offset 48))


(cffi:defctype model-quantize-params (:struct model-quantize-params))


(cffi:defcstruct (logit-bias :size 8)
  (token token :offset 0)
  (bias :float :offset 4))


(cffi:defctype logit-bias (:struct logit-bias))


(cffi:defcstruct (sampler-chain-params :size 1)
  (no-perf :char :offset 0))


(cffi:defctype sampler-chain-params (:struct sampler-chain-params))


(cffi:defcstruct (chat-message :size 16)
  (role :string :offset 0)
  (content :string :offset 8))


(cffi:defctype chat-message (:struct chat-message))


(cffi:defcfun ("llama_model_default_params" model-default-params)
    (:struct model-params)
  "struct llama_model_params llama_model_default_params();"
  (result (:struct model-params)))


(cffi:defcfun ("llama_context_default_params" context-default-params)
    (:struct context-params)
  "struct llama_context_params llama_context_default_params();"
  (result (:struct context-params)))


(cffi:defcfun ("llama_sampler_chain_default_params" sampler-chain-default-params)
    (:struct sampler-chain-params)
  "struct llama_sampler_chain_params llama_sampler_chain_default_params();"
  (result (:struct sampler-chain-params)))


(cffi:defcfun ("llama_model_quantize_default_params" model-quantize-default-params)
    (:struct model-quantize-params)
  "struct llama_model_quantize_params llama_model_quantize_default_params();"
  (result (:struct model-quantize-params)))


(cffi:defcfun ("llama_backend_init" backend-init)
    :void
  "void llama_backend_init();")


(cffi:defcfun ("llama_backend_free" backend-free)
    :void
  "void llama_backend_free();")


(cffi:defcfun ("llama_numa_init" numa-init)
    :void
  "void llama_numa_init(enum ggml_numa_strategy numa);"
  (numa ggml-numa-strategy))


(cffi:defcstruct context)


(cffi:defcfun ("llama_attach_threadpool" attach-threadpool)
    :void
  "void llama_attach_threadpool(struct llama_context* ctx, ggml_threadpool_t threadpool, ggml_threadpool_t threadpool_batch);"
  (ctx (:pointer (:struct context)))
  (threadpool ggml-threadpool-t)
  (threadpool-batch ggml-threadpool-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_detach_threadpool" detach-threadpool)
    :void
  "void llama_detach_threadpool(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defctype model-set-tensor-data-t (:pointer :void))


(cffi:defcstruct model)


(cffi:defcstruct gguf-context)


(cffi:defcfun ("llama_model_init_from_user" model-init-from-user)
    (:pointer (:struct model))
  "struct llama_model* llama_model_init_from_user(struct gguf_context* metadata, llama_model_set_tensor_data_t set_tensor_data, void* set_tensor_data_ud, struct llama_model_params params);"
  (metadata (:pointer (:struct gguf-context)))
  (set-tensor-data model-set-tensor-data-t)
  (set-tensor-data-ud (:pointer :void))
  (params (:struct model-params)))


(cffi:defcstruct model)


(cffi:defcfun ("llama_load_model_from_file" load-model-from-file)
    (:pointer (:struct model))
  "struct llama_model* llama_load_model_from_file(char* path_model, struct llama_model_params params);"
  (path-model :string)
  (params (:struct model-params)))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_load_from_file" model-load-from-file)
    (:pointer (:struct model))
  "struct llama_model* llama_model_load_from_file(char* path_model, struct llama_model_params params);"
  (path-model :string)
  (params (:struct model-params)))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_load_from_file_ptr" model-load-from-file-ptr)
    (:pointer (:struct model))
  "struct llama_model* llama_model_load_from_file_ptr(FILE* file, struct llama_model_params params);"
  (file (:pointer file))
  (params (:struct model-params)))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_load_from_splits" model-load-from-splits)
    (:pointer (:struct model))
  "struct llama_model* llama_model_load_from_splits(char** paths, size_t n_paths, struct llama_model_params params);"
  (paths (:pointer :string))
  (n-paths size-t)
  (params (:struct model-params)))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_save_to_file" model-save-to-file)
    :void
  "void llama_model_save_to_file(struct llama_model* model, char* path_model);"
  (model (:pointer (:struct model)))
  (path-model :string))


(cffi:defcstruct model)


(cffi:defcfun ("llama_free_model" free-model)
    :void
  "void llama_free_model(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_free" model-free)
    :void
  "void llama_model_free(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct context)


(cffi:defcstruct model)


(cffi:defcfun ("llama_init_from_model" init-from-model)
    (:pointer (:struct context))
  "struct llama_context* llama_init_from_model(struct llama_model* model, struct llama_context_params params);"
  (model (:pointer (:struct model)))
  (params (:struct context-params)))


(cffi:defcstruct context)


(cffi:defcstruct model)


(cffi:defcfun ("llama_new_context_with_model" new-context-with-model)
    (:pointer (:struct context))
  "struct llama_context* llama_new_context_with_model(struct llama_model* model, struct llama_context_params params);"
  (model (:pointer (:struct model)))
  (params (:struct context-params)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_free" free)
    :void
  "void llama_free(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcfun ("llama_time_us" time-us)
    int64-t
  "int64_t llama_time_us();")


(cffi:defcfun ("llama_max_devices" max-devices)
    size-t
  "size_t llama_max_devices();")


(cffi:defcfun ("llama_max_parallel_sequences" max-parallel-sequences)
    size-t
  "size_t llama_max_parallel_sequences();")


(cffi:defcfun ("llama_max_tensor_buft_overrides" max-tensor-buft-overrides)
    size-t
  "size_t llama_max_tensor_buft_overrides();")


(cffi:defcfun ("llama_supports_mmap" supports-mmap)
    :char
  "char llama_supports_mmap();")


(cffi:defcfun ("llama_supports_mlock" supports-mlock)
    :char
  "char llama_supports_mlock();")


(cffi:defcfun ("llama_supports_gpu_offload" supports-gpu-offload)
    :char
  "char llama_supports_gpu_offload();")


(cffi:defcfun ("llama_supports_rpc" supports-rpc)
    :char
  "char llama_supports_rpc();")


(cffi:defcstruct context)


(cffi:defcfun ("llama_n_ctx" n-ctx)
    uint32-t
  "uint32_t llama_n_ctx(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_n_ctx_seq" n-ctx-seq)
    uint32-t
  "uint32_t llama_n_ctx_seq(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_n_batch" n-batch)
    uint32-t
  "uint32_t llama_n_batch(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_n_ubatch" n-ubatch)
    uint32-t
  "uint32_t llama_n_ubatch(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_n_seq_max" n-seq-max)
    uint32-t
  "uint32_t llama_n_seq_max(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_n_rs_seq" n-rs-seq)
    uint32-t
  "uint32_t llama_n_rs_seq(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_n_ctx_train" n-ctx-train)
    int32-t
  "int32_t llama_n_ctx_train(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_n_embd" n-embd)
    int32-t
  "int32_t llama_n_embd(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_n_layer" n-layer)
    int32-t
  "int32_t llama_n_layer(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_n_head" n-head)
    int32-t
  "int32_t llama_n_head(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_n_vocab" n-vocab)
    int32-t
  "int32_t llama_n_vocab(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct model)


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_model" get-model)
    (:pointer (:struct model))
  "struct llama_model* llama_get_model(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_memory" get-memory)
    memory-t
  "llama_memory_t llama_get_memory(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_pooling_type" pooling-type)
    pooling-type
  "enum llama_pooling_type llama_pooling_type(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct vocab)


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_get_vocab" model-get-vocab)
    (:pointer (:struct vocab))
  "struct llama_vocab* llama_model_get_vocab(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_rope_type" model-rope-type)
    rope-type
  "enum llama_rope_type llama_model_rope_type(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_ctx_train" model-n-ctx-train)
    int32-t
  "int32_t llama_model_n_ctx_train(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_embd" model-n-embd)
    int32-t
  "int32_t llama_model_n_embd(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_embd_inp" model-n-embd-inp)
    int32-t
  "int32_t llama_model_n_embd_inp(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_embd_out" model-n-embd-out)
    int32-t
  "int32_t llama_model_n_embd_out(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_layer" model-n-layer)
    int32-t
  "int32_t llama_model_n_layer(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_head" model-n-head)
    int32-t
  "int32_t llama_model_n_head(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_head_kv" model-n-head-kv)
    int32-t
  "int32_t llama_model_n_head_kv(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_swa" model-n-swa)
    int32-t
  "int32_t llama_model_n_swa(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_rope_freq_scale_train" model-rope-freq-scale-train)
    :float
  "float llama_model_rope_freq_scale_train(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_cls_out" model-n-cls-out)
    uint32-t
  "uint32_t llama_model_n_cls_out(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_cls_label" model-cls-label)
    :string
  "char* llama_model_cls_label(struct llama_model* model, uint32_t i);"
  (model (:pointer (:struct model)))
  (i uint32-t))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_type" vocab-type)
    vocab-type
  "enum llama_vocab_type llama_vocab_type(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_n_tokens" vocab-n-tokens)
    int32-t
  "int32_t llama_vocab_n_tokens(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_meta_val_str" model-meta-val-str)
    int32-t
  "int32_t llama_model_meta_val_str(struct llama_model* model, char* key, char* buf, size_t buf_size);"
  (model (:pointer (:struct model)))
  (key :string)
  (buf :string)
  (buf-size size-t))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_meta_count" model-meta-count)
    int32-t
  "int32_t llama_model_meta_count(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcfun ("llama_model_meta_key_str" model-meta-key-str)
    :string
  "char* llama_model_meta_key_str(enum llama_model_meta_key key);"
  (key model-meta-key))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_meta_key_by_index" model-meta-key-by-index)
    int32-t
  "int32_t llama_model_meta_key_by_index(struct llama_model* model, int32_t i, char* buf, size_t buf_size);"
  (model (:pointer (:struct model)))
  (i int32-t)
  (buf :string)
  (buf-size size-t))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_meta_val_str_by_index" model-meta-val-str-by-index)
    int32-t
  "int32_t llama_model_meta_val_str_by_index(struct llama_model* model, int32_t i, char* buf, size_t buf_size);"
  (model (:pointer (:struct model)))
  (i int32-t)
  (buf :string)
  (buf-size size-t))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_desc" model-desc)
    int32-t
  "int32_t llama_model_desc(struct llama_model* model, char* buf, size_t buf_size);"
  (model (:pointer (:struct model)))
  (buf :string)
  (buf-size size-t))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_size" model-size)
    uint64-t
  "uint64_t llama_model_size(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_chat_template" model-chat-template)
    :string
  "char* llama_model_chat_template(struct llama_model* model, char* name);"
  (model (:pointer (:struct model)))
  (name :string))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_n_params" model-n-params)
    uint64-t
  "uint64_t llama_model_n_params(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_has_encoder" model-has-encoder)
    :char
  "char llama_model_has_encoder(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_has_decoder" model-has-decoder)
    :char
  "char llama_model_has_decoder(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_decoder_start_token" model-decoder-start-token)
    token
  "llama_token llama_model_decoder_start_token(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_is_recurrent" model-is-recurrent)
    :char
  "char llama_model_is_recurrent(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_is_hybrid" model-is-hybrid)
    :char
  "char llama_model_is_hybrid(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcstruct model)


(cffi:defcfun ("llama_model_is_diffusion" model-is-diffusion)
    :char
  "char llama_model_is_diffusion(struct llama_model* model);"
  (model (:pointer (:struct model))))


(cffi:defcfun ("llama_model_quantize" model-quantize)
    uint32-t
  "uint32_t llama_model_quantize(char* fname_inp, char* fname_out, llama_model_quantize_params* params);"
  (fname-inp :string)
  (fname-out :string)
  (params (:pointer model-quantize-params)))


(cffi:defcstruct adapter-lora)


(cffi:defcstruct model)


(cffi:defcfun ("llama_adapter_lora_init" adapter-lora-init)
    (:pointer (:struct adapter-lora))
  "struct llama_adapter_lora* llama_adapter_lora_init(struct llama_model* model, char* path_lora);"
  (model (:pointer (:struct model)))
  (path-lora :string))


(cffi:defcstruct adapter-lora)


(cffi:defcfun ("llama_adapter_meta_val_str" adapter-meta-val-str)
    int32-t
  "int32_t llama_adapter_meta_val_str(struct llama_adapter_lora* adapter, char* key, char* buf, size_t buf_size);"
  (adapter (:pointer (:struct adapter-lora)))
  (key :string)
  (buf :string)
  (buf-size size-t))


(cffi:defcstruct adapter-lora)


(cffi:defcfun ("llama_adapter_meta_count" adapter-meta-count)
    int32-t
  "int32_t llama_adapter_meta_count(struct llama_adapter_lora* adapter);"
  (adapter (:pointer (:struct adapter-lora))))


(cffi:defcstruct adapter-lora)


(cffi:defcfun ("llama_adapter_meta_key_by_index" adapter-meta-key-by-index)
    int32-t
  "int32_t llama_adapter_meta_key_by_index(struct llama_adapter_lora* adapter, int32_t i, char* buf, size_t buf_size);"
  (adapter (:pointer (:struct adapter-lora)))
  (i int32-t)
  (buf :string)
  (buf-size size-t))


(cffi:defcstruct adapter-lora)


(cffi:defcfun ("llama_adapter_meta_val_str_by_index" adapter-meta-val-str-by-index)
    int32-t
  "int32_t llama_adapter_meta_val_str_by_index(struct llama_adapter_lora* adapter, int32_t i, char* buf, size_t buf_size);"
  (adapter (:pointer (:struct adapter-lora)))
  (i int32-t)
  (buf :string)
  (buf-size size-t))


(cffi:defcstruct adapter-lora)


(cffi:defcfun ("llama_adapter_lora_free" adapter-lora-free)
    :void
  "void llama_adapter_lora_free(struct llama_adapter_lora* adapter);"
  (adapter (:pointer (:struct adapter-lora))))


(cffi:defcstruct adapter-lora)


(cffi:defcfun ("llama_adapter_get_alora_n_invocation_tokens" adapter-get-alora-n-invocation-tokens)
    uint64-t
  "uint64_t llama_adapter_get_alora_n_invocation_tokens(struct llama_adapter_lora* adapter);"
  (adapter (:pointer (:struct adapter-lora))))


(cffi:defcstruct adapter-lora)


(cffi:defcfun ("llama_adapter_get_alora_invocation_tokens" adapter-get-alora-invocation-tokens)
    (:pointer token)
  "llama_token* llama_adapter_get_alora_invocation_tokens(struct llama_adapter_lora* adapter);"
  (adapter (:pointer (:struct adapter-lora))))


(cffi:defcstruct context)


(cffi:defcstruct adapter-lora)


(cffi:defcfun ("llama_set_adapters_lora" set-adapters-lora)
    int32-t
  "int32_t llama_set_adapters_lora(struct llama_context* ctx, struct llama_adapter_lora** adapters, size_t n_adapters, float* scales);"
  (ctx (:pointer (:struct context)))
  (adapters (:pointer (:pointer (:struct adapter-lora))))
  (n-adapters size-t)
  (scales (:pointer :float)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_set_adapter_cvec" set-adapter-cvec)
    int32-t
  "int32_t llama_set_adapter_cvec(struct llama_context* ctx, float* data, size_t len, int32_t n_embd, int32_t il_start, int32_t il_end);"
  (ctx (:pointer (:struct context)))
  (data (:pointer :float))
  (len size-t)
  (n-embd int32-t)
  (il-start int32-t)
  (il-end int32-t))


(cffi:defcfun ("llama_memory_clear" memory-clear)
    :void
  "void llama_memory_clear(llama_memory_t mem, char data);"
  (mem memory-t)
  (data :char))


(cffi:defcfun ("llama_memory_seq_rm" memory-seq-rm)
    :char
  "char llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1);"
  (mem memory-t)
  (seq-id seq-id)
  (p0 pos)
  (p1 pos))


(cffi:defcfun ("llama_memory_seq_cp" memory-seq-cp)
    :void
  "void llama_memory_seq_cp(llama_memory_t mem, llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1);"
  (mem memory-t)
  (seq-id-src seq-id)
  (seq-id-dst seq-id)
  (p0 pos)
  (p1 pos))


(cffi:defcfun ("llama_memory_seq_keep" memory-seq-keep)
    :void
  "void llama_memory_seq_keep(llama_memory_t mem, llama_seq_id seq_id);"
  (mem memory-t)
  (seq-id seq-id))


(cffi:defcfun ("llama_memory_seq_add" memory-seq-add)
    :void
  "void llama_memory_seq_add(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1, llama_pos delta);"
  (mem memory-t)
  (seq-id seq-id)
  (p0 pos)
  (p1 pos)
  (delta pos))


(cffi:defcfun ("llama_memory_seq_div" memory-seq-div)
    :void
  "void llama_memory_seq_div(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1, int d);"
  (mem memory-t)
  (seq-id seq-id)
  (p0 pos)
  (p1 pos)
  (d :int))


(cffi:defcfun ("llama_memory_seq_pos_min" memory-seq-pos-min)
    pos
  "llama_pos llama_memory_seq_pos_min(llama_memory_t mem, llama_seq_id seq_id);"
  (mem memory-t)
  (seq-id seq-id))


(cffi:defcfun ("llama_memory_seq_pos_max" memory-seq-pos-max)
    pos
  "llama_pos llama_memory_seq_pos_max(llama_memory_t mem, llama_seq_id seq_id);"
  (mem memory-t)
  (seq-id seq-id))


(cffi:defcfun ("llama_memory_can_shift" memory-can-shift)
    :char
  "char llama_memory_can_shift(llama_memory_t mem);"
  (mem memory-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_get_size" state-get-size)
    size-t
  "size_t llama_state_get_size(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_state_size" get-state-size)
    size-t
  "size_t llama_get_state_size(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_get_data" state-get-data)
    size-t
  "size_t llama_state_get_data(struct llama_context* ctx, uint8_t* dst, size_t size);"
  (ctx (:pointer (:struct context)))
  (dst (:pointer uint8-t))
  (size size-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_copy_state_data" copy-state-data)
    size-t
  "size_t llama_copy_state_data(struct llama_context* ctx, uint8_t* dst);"
  (ctx (:pointer (:struct context)))
  (dst (:pointer uint8-t)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_set_data" state-set-data)
    size-t
  "size_t llama_state_set_data(struct llama_context* ctx, uint8_t* src, size_t size);"
  (ctx (:pointer (:struct context)))
  (src (:pointer uint8-t))
  (size size-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_set_state_data" set-state-data)
    size-t
  "size_t llama_set_state_data(struct llama_context* ctx, uint8_t* src);"
  (ctx (:pointer (:struct context)))
  (src (:pointer uint8-t)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_load_file" state-load-file)
    :char
  "char llama_state_load_file(struct llama_context* ctx, char* path_session, llama_token* tokens_out, size_t n_token_capacity, size_t* n_token_count_out);"
  (ctx (:pointer (:struct context)))
  (path-session :string)
  (tokens-out (:pointer token))
  (n-token-capacity size-t)
  (n-token-count-out (:pointer size-t)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_load_session_file" load-session-file)
    :char
  "char llama_load_session_file(struct llama_context* ctx, char* path_session, llama_token* tokens_out, size_t n_token_capacity, size_t* n_token_count_out);"
  (ctx (:pointer (:struct context)))
  (path-session :string)
  (tokens-out (:pointer token))
  (n-token-capacity size-t)
  (n-token-count-out (:pointer size-t)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_save_file" state-save-file)
    :char
  "char llama_state_save_file(struct llama_context* ctx, char* path_session, llama_token* tokens, size_t n_token_count);"
  (ctx (:pointer (:struct context)))
  (path-session :string)
  (tokens (:pointer token))
  (n-token-count size-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_save_session_file" save-session-file)
    :char
  "char llama_save_session_file(struct llama_context* ctx, char* path_session, llama_token* tokens, size_t n_token_count);"
  (ctx (:pointer (:struct context)))
  (path-session :string)
  (tokens (:pointer token))
  (n-token-count size-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_seq_get_size" state-seq-get-size)
    size-t
  "size_t llama_state_seq_get_size(struct llama_context* ctx, llama_seq_id seq_id);"
  (ctx (:pointer (:struct context)))
  (seq-id seq-id))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_seq_get_data" state-seq-get-data)
    size-t
  "size_t llama_state_seq_get_data(struct llama_context* ctx, uint8_t* dst, size_t size, llama_seq_id seq_id);"
  (ctx (:pointer (:struct context)))
  (dst (:pointer uint8-t))
  (size size-t)
  (seq-id seq-id))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_seq_set_data" state-seq-set-data)
    size-t
  "size_t llama_state_seq_set_data(struct llama_context* ctx, uint8_t* src, size_t size, llama_seq_id dest_seq_id);"
  (ctx (:pointer (:struct context)))
  (src (:pointer uint8-t))
  (size size-t)
  (dest-seq-id seq-id))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_seq_save_file" state-seq-save-file)
    size-t
  "size_t llama_state_seq_save_file(struct llama_context* ctx, char* filepath, llama_seq_id seq_id, llama_token* tokens, size_t n_token_count);"
  (ctx (:pointer (:struct context)))
  (filepath :string)
  (seq-id seq-id)
  (tokens (:pointer token))
  (n-token-count size-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_seq_load_file" state-seq-load-file)
    size-t
  "size_t llama_state_seq_load_file(struct llama_context* ctx, char* filepath, llama_seq_id dest_seq_id, llama_token* tokens_out, size_t n_token_capacity, size_t* n_token_count_out);"
  (ctx (:pointer (:struct context)))
  (filepath :string)
  (dest-seq-id seq-id)
  (tokens-out (:pointer token))
  (n-token-capacity size-t)
  (n-token-count-out (:pointer size-t)))


(cffi:defctype state-seq-flags :unsigned-int)


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_seq_get_size_ext" state-seq-get-size-ext)
    size-t
  "size_t llama_state_seq_get_size_ext(struct llama_context* ctx, llama_seq_id seq_id, llama_state_seq_flags flags);"
  (ctx (:pointer (:struct context)))
  (seq-id seq-id)
  (flags state-seq-flags))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_seq_get_data_ext" state-seq-get-data-ext)
    size-t
  "size_t llama_state_seq_get_data_ext(struct llama_context* ctx, uint8_t* dst, size_t size, llama_seq_id seq_id, llama_state_seq_flags flags);"
  (ctx (:pointer (:struct context)))
  (dst (:pointer uint8-t))
  (size size-t)
  (seq-id seq-id)
  (flags state-seq-flags))


(cffi:defcstruct context)


(cffi:defcfun ("llama_state_seq_set_data_ext" state-seq-set-data-ext)
    size-t
  "size_t llama_state_seq_set_data_ext(struct llama_context* ctx, uint8_t* src, size_t size, llama_seq_id dest_seq_id, llama_state_seq_flags flags);"
  (ctx (:pointer (:struct context)))
  (src (:pointer uint8-t))
  (size size-t)
  (dest-seq-id seq-id)
  (flags state-seq-flags))


(cffi:defcfun ("llama_batch_get_one" batch-get-one)
    (:struct batch)
  "struct llama_batch llama_batch_get_one(llama_token* tokens, int32_t n_tokens);"
  (result (:struct batch))
  (tokens (:pointer token))
  (n-tokens int32-t))


(cffi:defcfun ("llama_batch_init" batch-init)
    (:struct batch)
  "struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max);"
  (result (:struct batch))
  (n-tokens int32-t)
  (embd int32-t)
  (n-seq-max int32-t))


(cffi:defcfun ("llama_batch_free" batch-free)
    :void
  "void llama_batch_free(struct llama_batch batch);"
  (batch (:struct batch)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_encode" encode)
    int32-t
  "int32_t llama_encode(struct llama_context* ctx, struct llama_batch batch);"
  (ctx (:pointer (:struct context)))
  (batch (:struct batch)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_decode" decode)
    int32-t
  "int32_t llama_decode(struct llama_context* ctx, struct llama_batch batch);"
  (ctx (:pointer (:struct context)))
  (batch (:struct batch)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_set_n_threads" set-n-threads)
    :void
  "void llama_set_n_threads(struct llama_context* ctx, int32_t n_threads, int32_t n_threads_batch);"
  (ctx (:pointer (:struct context)))
  (n-threads int32-t)
  (n-threads-batch int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_n_threads" n-threads)
    int32-t
  "int32_t llama_n_threads(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_n_threads_batch" n-threads-batch)
    int32-t
  "int32_t llama_n_threads_batch(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_set_embeddings" set-embeddings)
    :void
  "void llama_set_embeddings(struct llama_context* ctx, char embeddings);"
  (ctx (:pointer (:struct context)))
  (embeddings :char))


(cffi:defcstruct context)


(cffi:defcfun ("llama_set_causal_attn" set-causal-attn)
    :void
  "void llama_set_causal_attn(struct llama_context* ctx, char causal_attn);"
  (ctx (:pointer (:struct context)))
  (causal-attn :char))


(cffi:defcstruct context)


(cffi:defcfun ("llama_set_warmup" set-warmup)
    :void
  "void llama_set_warmup(struct llama_context* ctx, char warmup);"
  (ctx (:pointer (:struct context)))
  (warmup :char))


(cffi:defcstruct context)


(cffi:defcfun ("llama_set_abort_callback" set-abort-callback)
    :void
  "void llama_set_abort_callback(struct llama_context* ctx, ggml_abort_callback abort_callback, void* abort_callback_data);"
  (ctx (:pointer (:struct context)))
  (abort-callback ggml-abort-callback)
  (abort-callback-data (:pointer :void)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_synchronize" synchronize)
    :void
  "void llama_synchronize(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_logits" get-logits)
    (:pointer :float)
  "float* llama_get_logits(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_logits_ith" get-logits-ith)
    (:pointer :float)
  "float* llama_get_logits_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_embeddings" get-embeddings)
    (:pointer :float)
  "float* llama_get_embeddings(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_embeddings_ith" get-embeddings-ith)
    (:pointer :float)
  "float* llama_get_embeddings_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_embeddings_seq" get-embeddings-seq)
    (:pointer :float)
  "float* llama_get_embeddings_seq(struct llama_context* ctx, llama_seq_id seq_id);"
  (ctx (:pointer (:struct context)))
  (seq-id seq-id))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_sampled_token_ith" get-sampled-token-ith)
    token
  "llama_token llama_get_sampled_token_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_sampled_probs_ith" get-sampled-probs-ith)
    (:pointer :float)
  "float* llama_get_sampled_probs_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_sampled_probs_count_ith" get-sampled-probs-count-ith)
    uint32-t
  "uint32_t llama_get_sampled_probs_count_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_sampled_logits_ith" get-sampled-logits-ith)
    (:pointer :float)
  "float* llama_get_sampled_logits_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_sampled_logits_count_ith" get-sampled-logits-count-ith)
    uint32-t
  "uint32_t llama_get_sampled_logits_count_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_sampled_candidates_ith" get-sampled-candidates-ith)
    (:pointer token)
  "llama_token* llama_get_sampled_candidates_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct context)


(cffi:defcfun ("llama_get_sampled_candidates_count_ith" get-sampled-candidates-count-ith)
    uint32-t
  "uint32_t llama_get_sampled_candidates_count_ith(struct llama_context* ctx, int32_t i);"
  (ctx (:pointer (:struct context)))
  (i int32-t))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_get_text" vocab-get-text)
    :string
  "char* llama_vocab_get_text(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_get_score" vocab-get-score)
    :float
  "float llama_vocab_get_score(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_get_attr" vocab-get-attr)
    token-attr
  "enum llama_token_attr llama_vocab_get_attr(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_is_eog" vocab-is-eog)
    :char
  "char llama_vocab_is_eog(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_is_control" vocab-is-control)
    :char
  "char llama_vocab_is_control(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_bos" vocab-bos)
    token
  "llama_token llama_vocab_bos(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_eos" vocab-eos)
    token
  "llama_token llama_vocab_eos(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_eot" vocab-eot)
    token
  "llama_token llama_vocab_eot(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_sep" vocab-sep)
    token
  "llama_token llama_vocab_sep(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_nl" vocab-nl)
    token
  "llama_token llama_vocab_nl(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_pad" vocab-pad)
    token
  "llama_token llama_vocab_pad(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_mask" vocab-mask)
    token
  "llama_token llama_vocab_mask(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_get_add_bos" vocab-get-add-bos)
    :char
  "char llama_vocab_get_add_bos(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_get_add_eos" vocab-get-add-eos)
    :char
  "char llama_vocab_get_add_eos(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_get_add_sep" vocab-get-add-sep)
    :char
  "char llama_vocab_get_add_sep(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_fim_pre" vocab-fim-pre)
    token
  "llama_token llama_vocab_fim_pre(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_fim_suf" vocab-fim-suf)
    token
  "llama_token llama_vocab_fim_suf(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_fim_mid" vocab-fim-mid)
    token
  "llama_token llama_vocab_fim_mid(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_fim_pad" vocab-fim-pad)
    token
  "llama_token llama_vocab_fim_pad(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_fim_rep" vocab-fim-rep)
    token
  "llama_token llama_vocab_fim_rep(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_fim_sep" vocab-fim-sep)
    token
  "llama_token llama_vocab_fim_sep(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_get_text" token-get-text)
    :string
  "char* llama_token_get_text(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_get_score" token-get-score)
    :float
  "float llama_token_get_score(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_get_attr" token-get-attr)
    token-attr
  "enum llama_token_attr llama_token_get_attr(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_is_eog" token-is-eog)
    :char
  "char llama_token_is_eog(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_is_control" token-is-control)
    :char
  "char llama_token_is_control(struct llama_vocab* vocab, llama_token token);"
  (vocab (:pointer (:struct vocab)))
  (token token))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_bos" token-bos)
    token
  "llama_token llama_token_bos(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_eos" token-eos)
    token
  "llama_token llama_token_eos(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_eot" token-eot)
    token
  "llama_token llama_token_eot(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_cls" token-cls)
    token
  "llama_token llama_token_cls(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_sep" token-sep)
    token
  "llama_token llama_token_sep(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_nl" token-nl)
    token
  "llama_token llama_token_nl(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_pad" token-pad)
    token
  "llama_token llama_token_pad(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_add_bos_token" add-bos-token)
    :char
  "char llama_add_bos_token(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_add_eos_token" add-eos-token)
    :char
  "char llama_add_eos_token(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_fim_pre" token-fim-pre)
    token
  "llama_token llama_token_fim_pre(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_fim_suf" token-fim-suf)
    token
  "llama_token llama_token_fim_suf(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_fim_mid" token-fim-mid)
    token
  "llama_token llama_token_fim_mid(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_fim_pad" token-fim-pad)
    token
  "llama_token llama_token_fim_pad(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_fim_rep" token-fim-rep)
    token
  "llama_token llama_token_fim_rep(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_fim_sep" token-fim-sep)
    token
  "llama_token llama_token_fim_sep(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_vocab_cls" vocab-cls)
    token
  "llama_token llama_vocab_cls(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_tokenize" tokenize)
    int32-t
  "int32_t llama_tokenize(struct llama_vocab* vocab, char* text, int32_t text_len, llama_token* tokens, int32_t n_tokens_max, char add_special, char parse_special);"
  (vocab (:pointer (:struct vocab)))
  (text :string)
  (text-len int32-t)
  (tokens (:pointer token))
  (n-tokens-max int32-t)
  (add-special :char)
  (parse-special :char))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_token_to_piece" token-to-piece)
    int32-t
  "int32_t llama_token_to_piece(struct llama_vocab* vocab, llama_token token, char* buf, int32_t length, int32_t lstrip, char special);"
  (vocab (:pointer (:struct vocab)))
  (token token)
  (buf :string)
  (length int32-t)
  (lstrip int32-t)
  (special :char))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_detokenize" detokenize)
    int32-t
  "int32_t llama_detokenize(struct llama_vocab* vocab, llama_token* tokens, int32_t n_tokens, char* text, int32_t text_len_max, char remove_special, char unparse_special);"
  (vocab (:pointer (:struct vocab)))
  (tokens (:pointer token))
  (n-tokens int32-t)
  (text :string)
  (text-len-max int32-t)
  (remove-special :char)
  (unparse-special :char))


(cffi:defcfun ("llama_chat_apply_template" chat-apply-template)
    int32-t
  "int32_t llama_chat_apply_template(char* tmpl, struct llama_chat_message* chat, size_t n_msg, char add_ass, char* buf, int32_t length);"
  (tmpl :string)
  (chat (:pointer (:struct chat-message)))
  (n-msg size-t)
  (add-ass :char)
  (buf :string)
  (length int32-t))


(cffi:defcfun ("llama_chat_builtin_templates" chat-builtin-templates)
    int32-t
  "int32_t llama_chat_builtin_templates(char** output, size_t len);"
  (output (:pointer :string))
  (len size-t))


(cffi:defcstruct (sampler-data :size 32)
  (logits (:pointer (:struct ggml-tensor)) :offset 0)
  (probs (:pointer (:struct ggml-tensor)) :offset 8)
  (sampled (:pointer (:struct ggml-tensor)) :offset 16)
  (candidates (:pointer (:struct ggml-tensor)) :offset 24))


(cffi:defcstruct context)


(cffi:defcfun ("llama_set_sampler" set-sampler)
    :char
  "char llama_set_sampler(struct llama_context* ctx, llama_seq_id seq_id, struct llama_sampler* smpl);"
  (ctx (:pointer (:struct context)))
  (seq-id seq-id)
  (smpl (:pointer (:struct sampler))))


(cffi:defcfun ("llama_sampler_init" sampler-init)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init(struct llama_sampler_i* iface, llama_sampler_context_t ctx);"
  (iface (:pointer (:struct sampler-i)))
  (ctx sampler-context-t))


(cffi:defcfun ("llama_sampler_name" sampler-name)
    :string
  "char* llama_sampler_name(struct llama_sampler* smpl);"
  (smpl (:pointer (:struct sampler))))


(cffi:defcfun ("llama_sampler_accept" sampler-accept)
    :void
  "void llama_sampler_accept(struct llama_sampler* smpl, llama_token token);"
  (smpl (:pointer (:struct sampler)))
  (token token))


(cffi:defcfun ("llama_sampler_apply" sampler-apply)
    :void
  "void llama_sampler_apply(struct llama_sampler* smpl, llama_token_data_array* cur_p);"
  (smpl (:pointer (:struct sampler)))
  (cur-p (:pointer token-data-array)))


(cffi:defcfun ("llama_sampler_reset" sampler-reset)
    :void
  "void llama_sampler_reset(struct llama_sampler* smpl);"
  (smpl (:pointer (:struct sampler))))


(cffi:defcfun ("llama_sampler_clone" sampler-clone)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_clone(struct llama_sampler* smpl);"
  (smpl (:pointer (:struct sampler))))


(cffi:defcfun ("llama_sampler_free" sampler-free)
    :void
  "void llama_sampler_free(struct llama_sampler* smpl);"
  (smpl (:pointer (:struct sampler))))


(cffi:defcfun ("llama_sampler_chain_init" sampler-chain-init)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_chain_init(struct llama_sampler_chain_params params);"
  (params (:struct sampler-chain-params)))


(cffi:defcfun ("llama_sampler_chain_add" sampler-chain-add)
    :void
  "void llama_sampler_chain_add(struct llama_sampler* chain, struct llama_sampler* smpl);"
  (chain (:pointer (:struct sampler)))
  (smpl (:pointer (:struct sampler))))


(cffi:defcfun ("llama_sampler_chain_get" sampler-chain-get)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_chain_get(struct llama_sampler* chain, int32_t i);"
  (chain (:pointer (:struct sampler)))
  (i int32-t))


(cffi:defcfun ("llama_sampler_chain_n" sampler-chain-n)
    :int
  "int llama_sampler_chain_n(struct llama_sampler* chain);"
  (chain (:pointer (:struct sampler))))


(cffi:defcfun ("llama_sampler_chain_remove" sampler-chain-remove)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_chain_remove(struct llama_sampler* chain, int32_t i);"
  (chain (:pointer (:struct sampler)))
  (i int32-t))


(cffi:defcfun ("llama_sampler_init_greedy" sampler-init-greedy)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_greedy();")


(cffi:defcfun ("llama_sampler_init_dist" sampler-init-dist)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_dist(uint32_t seed);"
  (seed uint32-t))


(cffi:defcfun ("llama_sampler_init_top_k" sampler-init-top-k)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_top_k(int32_t k);"
  (k int32-t))


(cffi:defcfun ("llama_sampler_init_top_p" sampler-init-top-p)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_top_p(float p, size_t min_keep);"
  (p :float)
  (min-keep size-t))


(cffi:defcfun ("llama_sampler_init_min_p" sampler-init-min-p)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_min_p(float p, size_t min_keep);"
  (p :float)
  (min-keep size-t))


(cffi:defcfun ("llama_sampler_init_typical" sampler-init-typical)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_typical(float p, size_t min_keep);"
  (p :float)
  (min-keep size-t))


(cffi:defcfun ("llama_sampler_init_temp" sampler-init-temp)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_temp(float t);"
  (t :float))


(cffi:defcfun ("llama_sampler_init_temp_ext" sampler-init-temp-ext)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_temp_ext(float t, float delta, float exponent);"
  (t :float)
  (delta :float)
  (exponent :float))


(cffi:defcfun ("llama_sampler_init_xtc" sampler-init-xtc)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_xtc(float p, float t, size_t min_keep, uint32_t seed);"
  (p :float)
  (t :float)
  (min-keep size-t)
  (seed uint32-t))


(cffi:defcfun ("llama_sampler_init_top_n_sigma" sampler-init-top-n-sigma)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_top_n_sigma(float n);"
  (n :float))


(cffi:defcfun ("llama_sampler_init_mirostat" sampler-init-mirostat)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_mirostat(int32_t n_vocab, uint32_t seed, float tau, float eta, int32_t m);"
  (n-vocab int32-t)
  (seed uint32-t)
  (tau :float)
  (eta :float)
  (m int32-t))


(cffi:defcfun ("llama_sampler_init_mirostat_v2" sampler-init-mirostat-v2)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_mirostat_v2(uint32_t seed, float tau, float eta);"
  (seed uint32-t)
  (tau :float)
  (eta :float))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_sampler_init_grammar" sampler-init-grammar)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_grammar(struct llama_vocab* vocab, char* grammar_str, char* grammar_root);"
  (vocab (:pointer (:struct vocab)))
  (grammar-str :string)
  (grammar-root :string))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_sampler_init_grammar_lazy" sampler-init-grammar-lazy)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_grammar_lazy(struct llama_vocab* vocab, char* grammar_str, char* grammar_root, char** trigger_words, size_t num_trigger_words, llama_token* trigger_tokens, size_t num_trigger_tokens);"
  (vocab (:pointer (:struct vocab)))
  (grammar-str :string)
  (grammar-root :string)
  (trigger-words (:pointer :string))
  (num-trigger-words size-t)
  (trigger-tokens (:pointer token))
  (num-trigger-tokens size-t))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_sampler_init_grammar_lazy_patterns" sampler-init-grammar-lazy-patterns)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_grammar_lazy_patterns(struct llama_vocab* vocab, char* grammar_str, char* grammar_root, char** trigger_patterns, size_t num_trigger_patterns, llama_token* trigger_tokens, size_t num_trigger_tokens);"
  (vocab (:pointer (:struct vocab)))
  (grammar-str :string)
  (grammar-root :string)
  (trigger-patterns (:pointer :string))
  (num-trigger-patterns size-t)
  (trigger-tokens (:pointer token))
  (num-trigger-tokens size-t))


(cffi:defcfun ("llama_sampler_init_penalties" sampler-init-penalties)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_penalties(int32_t penalty_last_n, float penalty_repeat, float penalty_freq, float penalty_present);"
  (penalty-last-n int32-t)
  (penalty-repeat :float)
  (penalty-freq :float)
  (penalty-present :float))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_sampler_init_dry" sampler-init-dry)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_dry(struct llama_vocab* vocab, int32_t n_ctx_train, float dry_multiplier, float dry_base, int32_t dry_allowed_length, int32_t dry_penalty_last_n, char** seq_breakers, size_t num_breakers);"
  (vocab (:pointer (:struct vocab)))
  (n-ctx-train int32-t)
  (dry-multiplier :float)
  (dry-base :float)
  (dry-allowed-length int32-t)
  (dry-penalty-last-n int32-t)
  (seq-breakers (:pointer :string))
  (num-breakers size-t))


(cffi:defcfun ("llama_sampler_init_adaptive_p" sampler-init-adaptive-p)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_adaptive_p(float target, float decay, uint32_t seed);"
  (target :float)
  (decay :float)
  (seed uint32-t))


(cffi:defcfun ("llama_sampler_init_logit_bias" sampler-init-logit-bias)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_logit_bias(int32_t n_vocab, int32_t n_logit_bias, llama_logit_bias* logit_bias);"
  (n-vocab int32-t)
  (n-logit-bias int32-t)
  (logit-bias (:pointer logit-bias)))


(cffi:defcstruct vocab)


(cffi:defcfun ("llama_sampler_init_infill" sampler-init-infill)
    (:pointer (:struct sampler))
  "struct llama_sampler* llama_sampler_init_infill(struct llama_vocab* vocab);"
  (vocab (:pointer (:struct vocab))))


(cffi:defcfun ("llama_sampler_get_seed" sampler-get-seed)
    uint32-t
  "uint32_t llama_sampler_get_seed(struct llama_sampler* smpl);"
  (smpl (:pointer (:struct sampler))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_sampler_sample" sampler-sample)
    token
  "llama_token llama_sampler_sample(struct llama_sampler* smpl, struct llama_context* ctx, int32_t idx);"
  (smpl (:pointer (:struct sampler)))
  (ctx (:pointer (:struct context)))
  (idx int32-t))


(cffi:defcfun ("llama_split_path" split-path)
    int32-t
  "int32_t llama_split_path(char* split_path, size_t maxlen, char* path_prefix, int32_t split_no, int32_t split_count);"
  (split-path :string)
  (maxlen size-t)
  (path-prefix :string)
  (split-no int32-t)
  (split-count int32-t))


(cffi:defcfun ("llama_split_prefix" split-prefix)
    int32-t
  "int32_t llama_split_prefix(char* split_prefix, size_t maxlen, char* split_path, int32_t split_no, int32_t split_count);"
  (split-prefix :string)
  (maxlen size-t)
  (split-path :string)
  (split-no int32-t)
  (split-count int32-t))


(cffi:defcfun ("llama_print_system_info" print-system-info)
    :string
  "char* llama_print_system_info();")


(cffi:defcfun ("llama_log_get" log-get)
    :void
  "void llama_log_get(ggml_log_callback* log_callback, void** user_data);"
  (log-callback (:pointer ggml-log-callback))
  (user-data (:pointer (:pointer :void))))


(cffi:defcfun ("llama_log_set" log-set)
    :void
  "void llama_log_set(ggml_log_callback log_callback, void* user_data);"
  (log-callback ggml-log-callback)
  (user-data (:pointer :void)))


(cffi:defcstruct (perf-context-data :size 48)
  (t-start-ms :double :offset 0)
  (t-load-ms :double :offset 8)
  (t-p-eval-ms :double :offset 16)
  (t-eval-ms :double :offset 24)
  (n-p-eval int32-t :offset 32)
  (n-eval int32-t :offset 36)
  (n-reused int32-t :offset 40))


(cffi:defcstruct (perf-sampler-data :size 16)
  (t-sample-ms :double :offset 0)
  (n-sample int32-t :offset 8))


(cffi:defcstruct context)


(cffi:defcfun ("llama_perf_context" perf-context)
    (:struct perf-context-data)
  "struct llama_perf_context_data llama_perf_context(struct llama_context* ctx);"
  (result (:struct perf-context-data))
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_perf_context_print" perf-context-print)
    :void
  "void llama_perf_context_print(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcstruct context)


(cffi:defcfun ("llama_perf_context_reset" perf-context-reset)
    :void
  "void llama_perf_context_reset(struct llama_context* ctx);"
  (ctx (:pointer (:struct context))))


(cffi:defcfun ("llama_perf_sampler" perf-sampler)
    (:struct perf-sampler-data)
  "struct llama_perf_sampler_data llama_perf_sampler(struct llama_sampler* chain);"
  (result (:struct perf-sampler-data))
  (chain (:pointer (:struct sampler))))


(cffi:defcfun ("llama_perf_sampler_print" perf-sampler-print)
    :void
  "void llama_perf_sampler_print(struct llama_sampler* chain);"
  (chain (:pointer (:struct sampler))))


(cffi:defcfun ("llama_perf_sampler_reset" perf-sampler-reset)
    :void
  "void llama_perf_sampler_reset(struct llama_sampler* chain);"
  (chain (:pointer (:struct sampler))))


(cffi:defctype opt-param-filter (:pointer :void))


(cffi:defcfun ("llama_opt_param_filter_all" opt-param-filter-all)
    :char
  "char llama_opt_param_filter_all(struct ggml_tensor* tensor, void* userdata);"
  (tensor (:pointer (:struct ggml-tensor)))
  (userdata (:pointer :void)))


(cffi:defcstruct (opt-params :size 48)
  (n-ctx-train uint32-t :offset 0)
  (param-filter opt-param-filter :offset 8)
  (param-filter-ud (:pointer :void) :offset 16)
  (get-opt-pars ggml-opt-get-optimizer-params :offset 24)
  (get-opt-pars-ud (:pointer :void) :offset 32)
  (optimizer-type ggml-opt-optimizer-type :offset 40))


(cffi:defcstruct context)


(cffi:defcstruct model)


(cffi:defcfun ("llama_opt_init" opt-init)
    :void
  "void llama_opt_init(struct llama_context* lctx, struct llama_model* model, struct llama_opt_params lopt_params);"
  (lctx (:pointer (:struct context)))
  (model (:pointer (:struct model)))
  (lopt-params (:struct opt-params)))


(cffi:defcstruct context)


(cffi:defcfun ("llama_opt_epoch" opt-epoch)
    :void
  "void llama_opt_epoch(struct llama_context* lctx, ggml_opt_dataset_t dataset, ggml_opt_result_t result_train, ggml_opt_result_t result_eval, int64_t idata_split, ggml_opt_epoch_callback callback_train, ggml_opt_epoch_callback callback_eval);"
  (lctx (:pointer (:struct context)))
  (dataset ggml-opt-dataset-t)
  (result-train ggml-opt-result-t)
  (result-eval ggml-opt-result-t)
  (idata-split int64-t)
  (callback-train ggml-opt-epoch-callback)
  (callback-eval ggml-opt-epoch-callback))


(common-lisp:export '+default-seed+ "%LLAMA")


(common-lisp:export '+file-magic-ggla+ "%LLAMA")


(common-lisp:export '+file-magic-ggsn+ "%LLAMA")


(common-lisp:export '+file-magic-ggsq+ "%LLAMA")


(common-lisp:export '+session-magic+ "%LLAMA")


(common-lisp:export '+session-version+ "%LLAMA")


(common-lisp:export '+state-seq-flags-none+ "%LLAMA")


(common-lisp:export '+state-seq-flags-on-device+ "%LLAMA")


(common-lisp:export '+state-seq-flags-partial-only+ "%LLAMA")


(common-lisp:export '+state-seq-flags-swa-only+ "%LLAMA")


(common-lisp:export '+state-seq-magic+ "%LLAMA")


(common-lisp:export '+state-seq-version+ "%LLAMA")


(common-lisp:export '+token-null+ "%LLAMA")


(common-lisp:export 'size-t "%LLAMA")


(common-lisp:export '%%int8-t "%LLAMA")


(common-lisp:export '%%uint8-t "%LLAMA")


(common-lisp:export '%%int32-t "%LLAMA")


(common-lisp:export '%%uint32-t "%LLAMA")


(common-lisp:export '%%int64-t "%LLAMA")


(common-lisp:export '%%uint64-t "%LLAMA")


(common-lisp:export 'int8-t "%LLAMA")


(common-lisp:export 'int32-t "%LLAMA")


(common-lisp:export 'int64-t "%LLAMA")


(common-lisp:export 'uint8-t "%LLAMA")


(common-lisp:export 'uint32-t "%LLAMA")


(common-lisp:export 'uint64-t "%LLAMA")


(common-lisp:export '%io-file "%LLAMA")


(common-lisp:export 'file "%LLAMA")


(common-lisp:export 'ggml-type "%LLAMA")


(common-lisp:export 'ggml-tensor "%LLAMA")


(common-lisp:export 'ggml-abort-callback "%LLAMA")


(common-lisp:export 'ggml-log-callback "%LLAMA")


(common-lisp:export 'ggml-threadpool-t "%LLAMA")


(common-lisp:export 'ggml-backend-buffer-type-t "%LLAMA")


(common-lisp:export 'ggml-backend-dev-t "%LLAMA")


(common-lisp:export 'ggml-backend-sched-eval-callback "%LLAMA")


(common-lisp:export 'ggml-numa-strategy "%LLAMA")


(common-lisp:export 'ggml-opt-dataset-t "%LLAMA")


(common-lisp:export 'ggml-opt-result-t "%LLAMA")


(common-lisp:export 'ggml-opt-optimizer-type "%LLAMA")


(common-lisp:export 'ggml-opt-get-optimizer-params "%LLAMA")


(common-lisp:export 'ggml-opt-epoch-callback "%LLAMA")


(common-lisp:export 'memory-t "%LLAMA")


(common-lisp:export 'pos "%LLAMA")


(common-lisp:export 'token "%LLAMA")


(common-lisp:export 'seq-id "%LLAMA")


(common-lisp:export 'vocab-type "%LLAMA")


(common-lisp:export 'rope-type "%LLAMA")


(common-lisp:export 'token-type "%LLAMA")


(common-lisp:export 'token-attr "%LLAMA")


(common-lisp:export 'ftype "%LLAMA")


(common-lisp:export 'rope-scaling-type "%LLAMA")


(common-lisp:export 'pooling-type "%LLAMA")


(common-lisp:export 'attention-type "%LLAMA")


(common-lisp:export 'flash-attn-type "%LLAMA")


(common-lisp:export 'flash-attn-type-name "%LLAMA")


(common-lisp:export 'split-mode "%LLAMA")


(common-lisp:export 'context-type "%LLAMA")


(common-lisp:export 'id "%LLAMA")


(common-lisp:export 'logit "%LLAMA")


(common-lisp:export 'p "%LLAMA")


(common-lisp:export 'token-data "%LLAMA")


(common-lisp:export 'data "%LLAMA")


(common-lisp:export 'size "%LLAMA")


(common-lisp:export 'selected "%LLAMA")


(common-lisp:export 'sorted "%LLAMA")


(common-lisp:export 'token-data-array "%LLAMA")


(common-lisp:export 'progress-callback "%LLAMA")


(common-lisp:export 'n-tokens "%LLAMA")


(common-lisp:export 'embd "%LLAMA")


(common-lisp:export 'n-seq-id "%LLAMA")


(common-lisp:export 'logits "%LLAMA")


(common-lisp:export 'batch "%LLAMA")


(common-lisp:export 'model-kv-override-type "%LLAMA")


(common-lisp:export 'model-meta-key "%LLAMA")


(common-lisp:export 'val-i64 "%LLAMA")


(common-lisp:export 'val-f64 "%LLAMA")


(common-lisp:export 'val-bool "%LLAMA")


(common-lisp:export 'val-str "%LLAMA")


(common-lisp:export 'model-kv-override-value "%LLAMA")


(common-lisp:export 'tag "%LLAMA")


(common-lisp:export 'key "%LLAMA")


(common-lisp:export 'model-kv-override "%LLAMA")


(common-lisp:export 'pattern "%LLAMA")


(common-lisp:export 'buft "%LLAMA")


(common-lisp:export 'model-tensor-buft-override "%LLAMA")


(common-lisp:export 'devices "%LLAMA")


(common-lisp:export 'tensor-buft-overrides "%LLAMA")


(common-lisp:export 'n-gpu-layers "%LLAMA")


(common-lisp:export 'main-gpu "%LLAMA")


(common-lisp:export 'tensor-split "%LLAMA")


(common-lisp:export 'progress-callback-user-data "%LLAMA")


(common-lisp:export 'kv-overrides "%LLAMA")


(common-lisp:export 'vocab-only "%LLAMA")


(common-lisp:export 'use-mmap "%LLAMA")


(common-lisp:export 'use-direct-io "%LLAMA")


(common-lisp:export 'use-mlock "%LLAMA")


(common-lisp:export 'check-tensors "%LLAMA")


(common-lisp:export 'use-extra-bufts "%LLAMA")


(common-lisp:export 'no-host "%LLAMA")


(common-lisp:export 'no-alloc "%LLAMA")


(common-lisp:export 'model-params "%LLAMA")


(common-lisp:export 'name "%LLAMA")


(common-lisp:export 'accept "%LLAMA")


(common-lisp:export 'apply "%LLAMA")


(common-lisp:export 'reset "%LLAMA")


(common-lisp:export 'clone "%LLAMA")


(common-lisp:export 'free "%LLAMA")


(common-lisp:export 'backend-init "%LLAMA")


(common-lisp:export 'backend-accept "%LLAMA")


(common-lisp:export 'backend-apply "%LLAMA")


(common-lisp:export 'backend-set-input "%LLAMA")


(common-lisp:export 'sampler-i "%LLAMA")


(common-lisp:export 'sampler-context-t "%LLAMA")


(common-lisp:export 'iface "%LLAMA")


(common-lisp:export 'ctx "%LLAMA")


(common-lisp:export 'sampler "%LLAMA")


(common-lisp:export 'sampler-seq-config "%LLAMA")


(common-lisp:export 'n-ctx "%LLAMA")


(common-lisp:export 'n-batch "%LLAMA")


(common-lisp:export 'n-ubatch "%LLAMA")


(common-lisp:export 'n-seq-max "%LLAMA")


(common-lisp:export 'n-rs-seq "%LLAMA")


(common-lisp:export 'n-outputs-max "%LLAMA")


(common-lisp:export 'n-threads "%LLAMA")


(common-lisp:export 'n-threads-batch "%LLAMA")


(common-lisp:export 'ctx-type "%LLAMA")


(common-lisp:export 'rope-freq-base "%LLAMA")


(common-lisp:export 'rope-freq-scale "%LLAMA")


(common-lisp:export 'yarn-ext-factor "%LLAMA")


(common-lisp:export 'yarn-attn-factor "%LLAMA")


(common-lisp:export 'yarn-beta-fast "%LLAMA")


(common-lisp:export 'yarn-beta-slow "%LLAMA")


(common-lisp:export 'yarn-orig-ctx "%LLAMA")


(common-lisp:export 'defrag-thold "%LLAMA")


(common-lisp:export 'cb-eval "%LLAMA")


(common-lisp:export 'cb-eval-user-data "%LLAMA")


(common-lisp:export 'type-k "%LLAMA")


(common-lisp:export 'type-v "%LLAMA")


(common-lisp:export 'abort-callback "%LLAMA")


(common-lisp:export 'abort-callback-data "%LLAMA")


(common-lisp:export 'embeddings "%LLAMA")


(common-lisp:export 'offload-kqv "%LLAMA")


(common-lisp:export 'no-perf "%LLAMA")


(common-lisp:export 'op-offload "%LLAMA")


(common-lisp:export 'swa-full "%LLAMA")


(common-lisp:export 'kv-unified "%LLAMA")


(common-lisp:export 'samplers "%LLAMA")


(common-lisp:export 'n-samplers "%LLAMA")


(common-lisp:export 'ctx-other "%LLAMA")


(common-lisp:export 'context-params "%LLAMA")


(common-lisp:export 'type "%LLAMA")


(common-lisp:export 'model-tensor-override "%LLAMA")


(common-lisp:export 'model-imatrix-data "%LLAMA")


(common-lisp:export 'nthread "%LLAMA")


(common-lisp:export 'output-tensor-type "%LLAMA")


(common-lisp:export 'token-embedding-type "%LLAMA")


(common-lisp:export 'allow-requantize "%LLAMA")


(common-lisp:export 'quantize-output-tensor "%LLAMA")


(common-lisp:export 'only-copy "%LLAMA")


(common-lisp:export 'pure "%LLAMA")


(common-lisp:export 'keep-split "%LLAMA")


(common-lisp:export 'dry-run "%LLAMA")


(common-lisp:export 'imatrix "%LLAMA")


(common-lisp:export 'tt-overrides "%LLAMA")


(common-lisp:export 'prune-layers "%LLAMA")


(common-lisp:export 'model-quantize-params "%LLAMA")


(common-lisp:export 'bias "%LLAMA")


(common-lisp:export 'logit-bias "%LLAMA")


(common-lisp:export 'sampler-chain-params "%LLAMA")


(common-lisp:export 'role "%LLAMA")


(common-lisp:export 'content "%LLAMA")


(common-lisp:export 'chat-message "%LLAMA")


(common-lisp:export 'model-default-params "%LLAMA")


(common-lisp:export 'context-default-params "%LLAMA")


(common-lisp:export 'sampler-chain-default-params "%LLAMA")


(common-lisp:export 'model-quantize-default-params "%LLAMA")


(common-lisp:export 'backend-free "%LLAMA")


(common-lisp:export 'numa-init "%LLAMA")


(common-lisp:export 'attach-threadpool "%LLAMA")


(common-lisp:export 'detach-threadpool "%LLAMA")


(common-lisp:export 'model-set-tensor-data-t "%LLAMA")


(common-lisp:export 'model-init-from-user "%LLAMA")


(common-lisp:export 'load-model-from-file "%LLAMA")


(common-lisp:export 'model-load-from-file "%LLAMA")


(common-lisp:export 'model-load-from-file-ptr "%LLAMA")


(common-lisp:export 'model-load-from-splits "%LLAMA")


(common-lisp:export 'model-save-to-file "%LLAMA")


(common-lisp:export 'free-model "%LLAMA")


(common-lisp:export 'model-free "%LLAMA")


(common-lisp:export 'init-from-model "%LLAMA")


(common-lisp:export 'new-context-with-model "%LLAMA")


(common-lisp:export 'time-us "%LLAMA")


(common-lisp:export 'max-devices "%LLAMA")


(common-lisp:export 'max-parallel-sequences "%LLAMA")


(common-lisp:export 'max-tensor-buft-overrides "%LLAMA")


(common-lisp:export 'supports-mmap "%LLAMA")


(common-lisp:export 'supports-mlock "%LLAMA")


(common-lisp:export 'supports-gpu-offload "%LLAMA")


(common-lisp:export 'supports-rpc "%LLAMA")


(common-lisp:export 'n-ctx-seq "%LLAMA")


(common-lisp:export 'n-ctx-train "%LLAMA")


(common-lisp:export 'n-embd "%LLAMA")


(common-lisp:export 'n-layer "%LLAMA")


(common-lisp:export 'n-head "%LLAMA")


(common-lisp:export 'n-vocab "%LLAMA")


(common-lisp:export 'get-model "%LLAMA")


(common-lisp:export 'get-memory "%LLAMA")


(common-lisp:export 'model-get-vocab "%LLAMA")


(common-lisp:export 'model-rope-type "%LLAMA")


(common-lisp:export 'model-n-ctx-train "%LLAMA")


(common-lisp:export 'model-n-embd "%LLAMA")


(common-lisp:export 'model-n-embd-inp "%LLAMA")


(common-lisp:export 'model-n-embd-out "%LLAMA")


(common-lisp:export 'model-n-layer "%LLAMA")


(common-lisp:export 'model-n-head "%LLAMA")


(common-lisp:export 'model-n-head-kv "%LLAMA")


(common-lisp:export 'model-n-swa "%LLAMA")


(common-lisp:export 'model-rope-freq-scale-train "%LLAMA")


(common-lisp:export 'model-n-cls-out "%LLAMA")


(common-lisp:export 'model-cls-label "%LLAMA")


(common-lisp:export 'vocab-n-tokens "%LLAMA")


(common-lisp:export 'model-meta-val-str "%LLAMA")


(common-lisp:export 'model-meta-count "%LLAMA")


(common-lisp:export 'model-meta-key-str "%LLAMA")


(common-lisp:export 'model-meta-key-by-index "%LLAMA")


(common-lisp:export 'model-meta-val-str-by-index "%LLAMA")


(common-lisp:export 'model-desc "%LLAMA")


(common-lisp:export 'model-size "%LLAMA")


(common-lisp:export 'model-chat-template "%LLAMA")


(common-lisp:export 'model-n-params "%LLAMA")


(common-lisp:export 'model-has-encoder "%LLAMA")


(common-lisp:export 'model-has-decoder "%LLAMA")


(common-lisp:export 'model-decoder-start-token "%LLAMA")


(common-lisp:export 'model-is-recurrent "%LLAMA")


(common-lisp:export 'model-is-hybrid "%LLAMA")


(common-lisp:export 'model-is-diffusion "%LLAMA")


(common-lisp:export 'model-quantize "%LLAMA")


(common-lisp:export 'adapter-lora-init "%LLAMA")


(common-lisp:export 'adapter-meta-val-str "%LLAMA")


(common-lisp:export 'adapter-meta-count "%LLAMA")


(common-lisp:export 'adapter-meta-key-by-index "%LLAMA")


(common-lisp:export 'adapter-meta-val-str-by-index "%LLAMA")


(common-lisp:export 'adapter-lora-free "%LLAMA")


(common-lisp:export 'adapter-get-alora-n-invocation-tokens "%LLAMA")


(common-lisp:export 'adapter-get-alora-invocation-tokens "%LLAMA")


(common-lisp:export 'set-adapters-lora "%LLAMA")


(common-lisp:export 'set-adapter-cvec "%LLAMA")


(common-lisp:export 'memory-clear "%LLAMA")


(common-lisp:export 'memory-seq-rm "%LLAMA")


(common-lisp:export 'memory-seq-cp "%LLAMA")


(common-lisp:export 'memory-seq-keep "%LLAMA")


(common-lisp:export 'memory-seq-add "%LLAMA")


(common-lisp:export 'memory-seq-div "%LLAMA")


(common-lisp:export 'memory-seq-pos-min "%LLAMA")


(common-lisp:export 'memory-seq-pos-max "%LLAMA")


(common-lisp:export 'memory-can-shift "%LLAMA")


(common-lisp:export 'state-get-size "%LLAMA")


(common-lisp:export 'get-state-size "%LLAMA")


(common-lisp:export 'state-get-data "%LLAMA")


(common-lisp:export 'copy-state-data "%LLAMA")


(common-lisp:export 'state-set-data "%LLAMA")


(common-lisp:export 'set-state-data "%LLAMA")


(common-lisp:export 'state-load-file "%LLAMA")


(common-lisp:export 'load-session-file "%LLAMA")


(common-lisp:export 'state-save-file "%LLAMA")


(common-lisp:export 'save-session-file "%LLAMA")


(common-lisp:export 'state-seq-get-size "%LLAMA")


(common-lisp:export 'state-seq-get-data "%LLAMA")


(common-lisp:export 'state-seq-set-data "%LLAMA")


(common-lisp:export 'state-seq-save-file "%LLAMA")


(common-lisp:export 'state-seq-load-file "%LLAMA")


(common-lisp:export 'state-seq-flags "%LLAMA")


(common-lisp:export 'state-seq-get-size-ext "%LLAMA")


(common-lisp:export 'state-seq-get-data-ext "%LLAMA")


(common-lisp:export 'state-seq-set-data-ext "%LLAMA")


(common-lisp:export 'batch-get-one "%LLAMA")


(common-lisp:export 'batch-init "%LLAMA")


(common-lisp:export 'batch-free "%LLAMA")


(common-lisp:export 'encode "%LLAMA")


(common-lisp:export 'decode "%LLAMA")


(common-lisp:export 'set-n-threads "%LLAMA")


(common-lisp:export 'set-embeddings "%LLAMA")


(common-lisp:export 'set-causal-attn "%LLAMA")


(common-lisp:export 'set-warmup "%LLAMA")


(common-lisp:export 'set-abort-callback "%LLAMA")


(common-lisp:export 'synchronize "%LLAMA")


(common-lisp:export 'get-logits "%LLAMA")


(common-lisp:export 'get-logits-ith "%LLAMA")


(common-lisp:export 'get-embeddings "%LLAMA")


(common-lisp:export 'get-embeddings-ith "%LLAMA")


(common-lisp:export 'get-embeddings-seq "%LLAMA")


(common-lisp:export 'get-sampled-token-ith "%LLAMA")


(common-lisp:export 'get-sampled-probs-ith "%LLAMA")


(common-lisp:export 'get-sampled-probs-count-ith "%LLAMA")


(common-lisp:export 'get-sampled-logits-ith "%LLAMA")


(common-lisp:export 'get-sampled-logits-count-ith "%LLAMA")


(common-lisp:export 'get-sampled-candidates-ith "%LLAMA")


(common-lisp:export 'get-sampled-candidates-count-ith "%LLAMA")


(common-lisp:export 'vocab-get-text "%LLAMA")


(common-lisp:export 'vocab-get-score "%LLAMA")


(common-lisp:export 'vocab-get-attr "%LLAMA")


(common-lisp:export 'vocab-is-eog "%LLAMA")


(common-lisp:export 'vocab-is-control "%LLAMA")


(common-lisp:export 'vocab-bos "%LLAMA")


(common-lisp:export 'vocab-eos "%LLAMA")


(common-lisp:export 'vocab-eot "%LLAMA")


(common-lisp:export 'vocab-sep "%LLAMA")


(common-lisp:export 'vocab-nl "%LLAMA")


(common-lisp:export 'vocab-pad "%LLAMA")


(common-lisp:export 'vocab-mask "%LLAMA")


(common-lisp:export 'vocab-get-add-bos "%LLAMA")


(common-lisp:export 'vocab-get-add-eos "%LLAMA")


(common-lisp:export 'vocab-get-add-sep "%LLAMA")


(common-lisp:export 'vocab-fim-pre "%LLAMA")


(common-lisp:export 'vocab-fim-suf "%LLAMA")


(common-lisp:export 'vocab-fim-mid "%LLAMA")


(common-lisp:export 'vocab-fim-pad "%LLAMA")


(common-lisp:export 'vocab-fim-rep "%LLAMA")


(common-lisp:export 'vocab-fim-sep "%LLAMA")


(common-lisp:export 'token-get-text "%LLAMA")


(common-lisp:export 'token-get-score "%LLAMA")


(common-lisp:export 'token-get-attr "%LLAMA")


(common-lisp:export 'token-is-eog "%LLAMA")


(common-lisp:export 'token-is-control "%LLAMA")


(common-lisp:export 'token-bos "%LLAMA")


(common-lisp:export 'token-eos "%LLAMA")


(common-lisp:export 'token-eot "%LLAMA")


(common-lisp:export 'token-cls "%LLAMA")


(common-lisp:export 'token-sep "%LLAMA")


(common-lisp:export 'token-nl "%LLAMA")


(common-lisp:export 'token-pad "%LLAMA")


(common-lisp:export 'add-bos-token "%LLAMA")


(common-lisp:export 'add-eos-token "%LLAMA")


(common-lisp:export 'token-fim-pre "%LLAMA")


(common-lisp:export 'token-fim-suf "%LLAMA")


(common-lisp:export 'token-fim-mid "%LLAMA")


(common-lisp:export 'token-fim-pad "%LLAMA")


(common-lisp:export 'token-fim-rep "%LLAMA")


(common-lisp:export 'token-fim-sep "%LLAMA")


(common-lisp:export 'vocab-cls "%LLAMA")


(common-lisp:export 'tokenize "%LLAMA")


(common-lisp:export 'token-to-piece "%LLAMA")


(common-lisp:export 'detokenize "%LLAMA")


(common-lisp:export 'chat-apply-template "%LLAMA")


(common-lisp:export 'chat-builtin-templates "%LLAMA")


(common-lisp:export 'probs "%LLAMA")


(common-lisp:export 'sampled "%LLAMA")


(common-lisp:export 'candidates "%LLAMA")


(common-lisp:export 'sampler-data "%LLAMA")


(common-lisp:export 'set-sampler "%LLAMA")


(common-lisp:export 'sampler-init "%LLAMA")


(common-lisp:export 'sampler-name "%LLAMA")


(common-lisp:export 'sampler-accept "%LLAMA")


(common-lisp:export 'sampler-apply "%LLAMA")


(common-lisp:export 'sampler-reset "%LLAMA")


(common-lisp:export 'sampler-clone "%LLAMA")


(common-lisp:export 'sampler-free "%LLAMA")


(common-lisp:export 'sampler-chain-init "%LLAMA")


(common-lisp:export 'sampler-chain-add "%LLAMA")


(common-lisp:export 'sampler-chain-get "%LLAMA")


(common-lisp:export 'sampler-chain-n "%LLAMA")


(common-lisp:export 'sampler-chain-remove "%LLAMA")


(common-lisp:export 'sampler-init-greedy "%LLAMA")


(common-lisp:export 'sampler-init-dist "%LLAMA")


(common-lisp:export 'sampler-init-top-k "%LLAMA")


(common-lisp:export 'sampler-init-top-p "%LLAMA")


(common-lisp:export 'sampler-init-min-p "%LLAMA")


(common-lisp:export 'sampler-init-typical "%LLAMA")


(common-lisp:export 'sampler-init-temp "%LLAMA")


(common-lisp:export 'sampler-init-temp-ext "%LLAMA")


(common-lisp:export 'sampler-init-xtc "%LLAMA")


(common-lisp:export 'sampler-init-top-n-sigma "%LLAMA")


(common-lisp:export 'sampler-init-mirostat "%LLAMA")


(common-lisp:export 'sampler-init-mirostat-v2 "%LLAMA")


(common-lisp:export 'sampler-init-grammar "%LLAMA")


(common-lisp:export 'sampler-init-grammar-lazy "%LLAMA")


(common-lisp:export 'sampler-init-grammar-lazy-patterns "%LLAMA")


(common-lisp:export 'sampler-init-penalties "%LLAMA")


(common-lisp:export 'sampler-init-dry "%LLAMA")


(common-lisp:export 'sampler-init-adaptive-p "%LLAMA")


(common-lisp:export 'sampler-init-logit-bias "%LLAMA")


(common-lisp:export 'sampler-init-infill "%LLAMA")


(common-lisp:export 'sampler-get-seed "%LLAMA")


(common-lisp:export 'sampler-sample "%LLAMA")


(common-lisp:export 'split-path "%LLAMA")


(common-lisp:export 'split-prefix "%LLAMA")


(common-lisp:export 'print-system-info "%LLAMA")


(common-lisp:export 'log-get "%LLAMA")


(common-lisp:export 'log-set "%LLAMA")


(common-lisp:export 't-start-ms "%LLAMA")


(common-lisp:export 't-load-ms "%LLAMA")


(common-lisp:export 't-p-eval-ms "%LLAMA")


(common-lisp:export 't-eval-ms "%LLAMA")


(common-lisp:export 'n-p-eval "%LLAMA")


(common-lisp:export 'n-eval "%LLAMA")


(common-lisp:export 'n-reused "%LLAMA")


(common-lisp:export 'perf-context-data "%LLAMA")


(common-lisp:export 't-sample-ms "%LLAMA")


(common-lisp:export 'n-sample "%LLAMA")


(common-lisp:export 'perf-sampler-data "%LLAMA")


(common-lisp:export 'perf-context "%LLAMA")


(common-lisp:export 'perf-context-print "%LLAMA")


(common-lisp:export 'perf-context-reset "%LLAMA")


(common-lisp:export 'perf-sampler "%LLAMA")


(common-lisp:export 'perf-sampler-print "%LLAMA")


(common-lisp:export 'perf-sampler-reset "%LLAMA")


(common-lisp:export 'opt-param-filter "%LLAMA")


(common-lisp:export 'opt-param-filter-all "%LLAMA")


(common-lisp:export 'param-filter "%LLAMA")


(common-lisp:export 'param-filter-ud "%LLAMA")


(common-lisp:export 'get-opt-pars "%LLAMA")


(common-lisp:export 'get-opt-pars-ud "%LLAMA")


(common-lisp:export 'optimizer-type "%LLAMA")


(common-lisp:export 'opt-params "%LLAMA")


(common-lisp:export 'opt-init "%LLAMA")


(common-lisp:export 'opt-epoch "%LLAMA")

